id = 'perl'
name = 'Perl'
description = "Perl support"
version = '0.1.1'
schema_version = 1
authors = ["Veesh <rabbiveesh@gmail.com>"]
repository = "https://github.com/tree-sitter-perl/zed-perl"
languages = ["languages/perl", "languages/pod"]

[grammars.perl]
repository = "https://github.com/tree-sitter-perl/tree-sitter-perl"
rev = "465983954cae2d2f984eae82de5ed5f11ca291dc"

[grammars.pod]
repository = "https://github.com/tree-sitter-perl/tree-sitter-pod"
rev = "0bf8387987c21bf2f8ed41d2575a8f22b139687f"

[language_servers.perlnavigator-server]
name = "Perl Navigator"
language = "Perl"

